[CmdletBinding()]
param(
  [Parameter(Mandatory=$true)][string]$SubscriptionId,
  [Parameter(Mandatory=$true)][string]$TenantId,
  [Parameter(Mandatory=$true)][string]$ResourceGroup,
  [Parameter(Mandatory=$true)][string]$Location,
  [Parameter(Mandatory=$true)][string]$BotName,
  [Parameter(Mandatory=$true)][string]$EndpointUrl,
  [string]$EnvOutputPath = "../.env.generated"
)

$ErrorActionPreference = 'Stop'

function Require-Cli {
  param([string]$Name)
  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
    throw "Required CLI not found: $Name"
  }
}

Require-Cli -Name az

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$bootstrap = Join-Path $scriptDir "01-azure-bot-bootstrap.ps1"
$validate = Join-Path $scriptDir "03-validate-deployment.ps1"

Write-Host "==> Running Azure bootstrap"
$bootstrapOutput = & pwsh $bootstrap `
  -SubscriptionId $SubscriptionId `
  -TenantId $TenantId `
  -ResourceGroup $ResourceGroup `
  -Location $Location `
  -BotName $BotName `
  -EndpointUrl $EndpointUrl 2>&1

$appId = ($bootstrapOutput | Select-String -Pattern '^MICROSOFT_APP_ID=' | Select-Object -Last 1).ToString().Split('=')[1]
$appPassword = ($bootstrapOutput | Select-String -Pattern '^MICROSOFT_APP_PASSWORD=' | Select-Object -Last 1).ToString().Split('=')[1]
$tenant = ($bootstrapOutput | Select-String -Pattern '^AZURE_TENANT_ID=' | Select-Object -Last 1).ToString().Split('=')[1]

if (-not $appId -or -not $appPassword) {
  throw "Could not parse app credentials from bootstrap output. Raw output:`n$($bootstrapOutput -join "`n")"
}

Write-Host "==> Running validation"
& pwsh $validate `
  -SubscriptionId $SubscriptionId `
  -ResourceGroup $ResourceGroup `
  -BotName $BotName `
  -EndpointUrl $EndpointUrl

$resolvedEnvPath = Resolve-Path (Join-Path $scriptDir $EnvOutputPath) -ErrorAction SilentlyContinue
if (-not $resolvedEnvPath) {
  $resolvedEnvPath = Join-Path $scriptDir $EnvOutputPath
}

$envContent = @"
# Generated by scripts/deploy-all.ps1
# Move/copy these into your OpenClaw Teams channel config/env.

MICROSOFT_APP_ID=$appId
MICROSOFT_APP_PASSWORD=$appPassword
AZURE_TENANT_ID=$tenant
TEAMS_BOT_ENDPOINT=$EndpointUrl
TEAMS_BOT_NAME=$BotName
AZURE_SUBSCRIPTION_ID=$SubscriptionId
AZURE_RESOURCE_GROUP=$ResourceGroup
"@

$envDir = Split-Path -Parent $resolvedEnvPath
if (-not (Test-Path $envDir)) { New-Item -ItemType Directory -Path $envDir -Force | Out-Null }
Set-Content -Path $resolvedEnvPath -Value $envContent -NoNewline

Write-Host ""
Write-Host "==> Done"
Write-Host "Generated env file: $resolvedEnvPath"
Write-Host "IMPORTANT: Treat this file as secret (contains client secret)."
